### ISSUE TITLE
How can i compile it 

### ISSUE THREAD

**Issue by ayuuuvauuu** [johnBuffer/UnitedEngine#2]
Can u give tell me how can i complie the projects, coz i do not use c++ and i am a noob. Tell me if u want any more info

**Comment by ayuuuvauuu** [comment]
And when i try to compile it gives me these errors

Commands ran:

cmake .
make 

Error:

Scanning dependencies of target UnitedEngine
[ 20%] Building CXX object CMakeFiles/UnitedEngine.dir/lib/Swarm/src/worker.cpp.o
In file included from /home/ayu/Code/random/UnitedEngine/lib/Swarm/src/worker.cpp:3:
/home/ayu/Code/random/UnitedEngine/lib/Swarm/include/swarm.hpp: In member function ‘swrm::WorkGroup swrm::Swarm::execute(swrm::WorkerFunction, uint32_t)’:
/home/ayu/Code/random/UnitedEngine/lib/Swarm/include/swarm.hpp:53:25: error: ‘make_unique’ is not a member of ‘std’
   53 |   return WorkGroup(std::make_unique<ExecutionGroup>(job, group_size, m_available_workers));
      |                         ^~~~~~~~~~~
/home/ayu/Code/random/UnitedEngine/lib/Swarm/include/swarm.hpp:53:25: note: ‘std::make_unique’ is only available from C++14 onwards
/home/ayu/Code/random/UnitedEngine/lib/Swarm/include/swarm.hpp:53:19: error: expected primary-expression before ‘(’ token
   53 |   return WorkGroup(std::make_unique<ExecutionGroup>(job, group_size, m_available_workers));
      |                   ^
/home/ayu/Code/random/UnitedEngine/lib/Swarm/include/swarm.hpp:53:25: error: ‘make_unique’ is not a member of ‘std’
   53 |   return WorkGroup(std::make_unique<ExecutionGroup>(job, group_size, m_available_workers));
      |                         ^~~~~~~~~~~
/home/ayu/Code/random/UnitedEngine/lib/Swarm/include/swarm.hpp:53:25: note: ‘std::make_unique’ is only available from C++14 onwards
/home/ayu/Code/random/UnitedEngine/lib/Swarm/include/swarm.hpp:53:51: error: expected primary-expression before ‘>’ token
   53 |   return WorkGroup(std::make_unique<ExecutionGroup>(job, group_size, m_available_workers));
      |                                                   ^
make[2]: *** [CMakeFiles/UnitedEngine.dir/build.make:63: CMakeFiles/UnitedEngine.dir/lib/Swarm/src/worker.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/UnitedEngine.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

Version:

c++ --version, output
c++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

g++ --version, output

g++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

gcc --version, output

gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

cmake --verison, output

cmake version 3.16.3

CMake suite maintained and supported by Kitware (kitware.com/cmake).

Hope u can help me

**Comment by KosmosisDire** [comment]
I am not a cmake expert, but if you read the error messages it says that you need c++ version 14 or higher

**Comment by ayuuuvauuu** [comment]
thx
